### ISSUE TITLE
Decouple ES from Aggregates

### ISSUE THREAD

**Issue by codeliner** [prooph/event-store#19]
This is the epic for a major change in the EventStore library. From version 0.5.0 on the ES will only handle event streams. The repository and aggregate type concept will be removed. But the library will continue to support aggregates and their repositories. Different StreamStrategies will be available to support translation from aggregates to streams and back and to organize events of the aggregates in one or more streams.
## Tasks
- [ ] #20 - Remove AggregateType
- [ ] #22 - Remove Repository Handling
- [ ] #23 - Default Stream Strategies
- [ ] #24 - Link Events In Projection Streams
- [ ] #25 - Handle Event Meta Data
